sudo apt install ca-certificates

- name: "manage worker1 and 2"
  hosts: all
  become: true
  tasks:
  - name: "ensure Irshad user exists"
    user:
      name: Irshad
      state: present
  - name: "ensure shivani user exists"
    user:
      name: sivani
      state: present

      
